# Dependabot configuration for Scratch Pad
# Phase 2.1: Fixed grouping and comprehensive patterns
# NOTE: Configuration changes trigger immediate PR creation, bypassing schedule limits
version: 2
updates:
  # JavaScript/TypeScript dependencies (Frontend)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3  # Reduced to prevent overload
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Comprehensive dependency grouping
    groups:
      # All development dependencies (minor/patch only)
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      # Production dependencies - UI components
      ui-components:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
          - "class-variance-authority"
          - "clsx"
          - "tailwind-merge"
        update-types:
          - "minor"
          - "patch"
      # Production dependencies - Tauri ecosystem
      tauri-frontend:
        patterns:
          - "@tauri-apps/*"
        update-types:
          - "minor"
          - "patch"
      # Production dependencies - Other libraries
      prod-utilities:
        patterns:
          - "zustand"
          - "react-window"
          - "@types/react-window"
        exclude-patterns:
          - "@radix-ui/*"
          - "@tauri-apps/*"
          - "react*"
        update-types:
          - "minor"
          - "patch"
    # Comprehensive ignore rules for stability
    ignore:
      # Core React ecosystem - no major updates
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react-dom"
        update-types: ["version-update:semver-major"]
      # Build tools - no major updates without testing
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@vitejs/plugin-react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vitest"
        update-types: ["version-update:semver-major"]
      # Other major updates to review manually
      - dependency-name: "react-window"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@tauri-apps/api"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@tauri-apps/cli"
        update-types: ["version-update:semver-major"]
      # TypeScript - stay on 5.7.x
      - dependency-name: "typescript"
        versions: [">5.7.0"]
    
  # Rust dependencies (Backend)  
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 2  # Reduced to prevent overload
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "deps(rust)"
      include: "scope"
    # Group related Rust dependencies
    groups:
      # Tauri and plugins
      tauri-ecosystem:
        patterns:
          - "tauri*"
          - "@tauri-apps/*"
        update-types:
          - "minor"
          - "patch"
      # Async runtime dependencies
      async-runtime:
        patterns:
          - "tokio*"
          - "async-*"
          - "futures*"
        update-types:
          - "minor"
          - "patch"
      # Testing dependencies
      rust-testing:
        patterns:
          - "mockall*"
          - "tempfile"
          - "criterion"
        update-types:
          - "minor"
          - "patch"
    # Ignore major updates for stability
    ignore:
      - dependency-name: "tauri"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tauri-plugin-*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tokio"
        update-types: ["version-update:semver-major"]
      - dependency-name: "serde"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlx"
        update-types: ["version-update:semver-major"]
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
    open-pull-requests-limit: 1  # Minimal to prevent overload
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
    # Group all actions updates
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

# Phase 2.1 Configuration:
# - Reduced PR limits: 3 npm, 2 cargo, 1 actions (was 5/3/2)
# - Comprehensive grouping for ALL dependency types
# - Extensive ignore rules for major updates
# - Note: Config changes trigger immediate PR creation surge
# See internal-docs/CODEQL_DEPENDABOT_INTEGRATION_PLAN.md for full roadmap