# Dependabot configuration for Scratch Pad
# Phase 0/1: Start with security updates only, limited PR count
version: 2
updates:
  # JavaScript/TypeScript dependencies (Frontend)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 2  # Start small
    labels:
      - "dependencies"
      - "security"
      - "javascript"
    commit-message:
      prefix: "sec"
      include: "scope"
    # Phase 1: Security updates only
    allow:
      - dependency-type: "security"
    
  # Rust dependencies (Backend)  
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 2  # Start small
    labels:
      - "dependencies"
      - "security"
      - "rust"
    commit-message:
      prefix: "sec(rust)"
      include: "scope"
    # Phase 1: Security updates only
    allow:
      - dependency-type: "security"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "ci"
      - "security"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"

# Note: This is the Phase 1 configuration focused on security updates only.
# In Phase 2, we'll expand to include version updates with proper grouping.
# See internal-docs/CODEQL_DEPENDABOT_INTEGRATION_PLAN.md for the full roadmap.