[env]
# CI-specific environment variables
RUST_TEST_THREADS = { value = "2", condition = { env = "CI", value = "true" } }
RUST_BACKTRACE = { value = "1", condition = { env = "CI", value = "true" } }

[target.'cfg(all())']
# Optimize for CI execution
rustflags = ["-C", "opt-level=0", "-C", "debuginfo=0"]

[profile.test]
# CI-optimized test profile
opt-level = 0
debug = false
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false