name: 'Install Linux Dependencies'
description: 'Install Linux system dependencies for Tauri application builds'
inputs:
  additional-packages:
    description: 'Additional apt packages to install (space-separated)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Update package lists
      shell: bash
      run: sudo apt-get update

    - name: Install Linux dependencies
      shell: bash
      run: |
        # Version-specific WebKit installation for Ubuntu compatibility
        if [ "$(lsb_release -rs)" = "24.04" ]; then
          sudo apt-get install -y libwebkit2gtk-4.1-dev
        else
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev
        fi
        
        # Common dependencies (platform-agnostic)
        sudo apt-get install -y \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          libssl-dev \
          pkg-config
        
        # Install additional packages if specified
        if [ -n "${{ inputs.additional-packages }}" ]; then
          sudo apt-get install -y ${{ inputs.additional-packages }}
        fi