name: Essential Checks Only

on:
  pull_request:
    branches: [main, develop]

jobs:
  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-node-pnpm
      - name: TypeScript Check
        run: pnpm type-check

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-node-pnpm
      - name: ESLint Check
        run: pnpm lint

  build:
    name: Build Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-node-pnpm
      - uses: ./.github/actions/setup-rust
      - name: Build Frontend
        run: pnpm build
      - name: Build Backend
        working-directory: src-tauri
        run: cargo build --release

  basic-test:
    name: Basic Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-node-pnpm
      - name: Run Core Tests
        run: |
          # Run only the most stable tests
          pnpm test -- --run --reporter=verbose \
            --exclude="**/CommandPalette*" \
            --exclude="**/ScratchPadApp*" \
            --maxWorkers=2

  rust-check:
    name: Rust Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-rust
      - uses: ./.github/actions/install-linux-deps
      - name: Rust Format Check
        working-directory: src-tauri
        run: cargo fmt -- --check
      - name: Rust Clippy Check
        working-directory: src-tauri
        run: cargo clippy -- -D warnings || true