name: Nightly Build

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Check for changes in last 24 hours
        id: check
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
          else
            CHANGES=$(git log --since="24 hours ago" --oneline | wc -l)
            if [ $CHANGES -gt 0 ]; then
              echo "should_build=true" >> $GITHUB_OUTPUT
            else
              echo "should_build=false" >> $GITHUB_OUTPUT
            fi
          fi

  nightly-build:
    name: Nightly Build (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}
    needs: check-changes
    if: needs.check-changes.outputs.should_build == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            os: 'macos-latest'
            target: 'universal-apple-darwin'
          - platform: 'ubuntu-22.04'
            os: 'ubuntu-22.04'
            target: 'x86_64-unknown-linux-gnu'
          - platform: 'windows-latest'
            os: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js and PNPM
        uses: ./.github/actions/setup-node-pnpm

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-rust

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        uses: ./.github/actions/install-linux-deps

      - name: Run tests with performance monitoring
        uses: ./.github/actions/run-tests
        with:
          run-frontend-tests: 'true'
          run-backend-tests: 'true'
          run-integration-tests: 'false'
          performance-monitoring: 'true'
          platform: ${{ matrix.platform }}

      - name: Build frontend
        uses: ./.github/actions/build-frontend
        with:
          run-tests: 'false'
          run-type-check: 'false'
          run-lint: 'false'
          build-production: 'true'

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0.5.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: 'nightly-${{ github.run_number }}'
          releaseName: 'Nightly Build ${{ github.run_number }}'
          releaseBody: |
            Automated nightly build from commit ${{ github.sha }}.
            
            **⚠️ This is a development build and may be unstable.**
            
            Changes since last release:
            ${{ github.event.head_commit.message }}
          releaseDraft: false
          prerelease: true
          args: --target ${{ matrix.target }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-${{ matrix.platform }}
          path: src-tauri/target/release/bundle/
          retention-days: 7