name: Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run security scan daily at 3 AM UTC
    - cron: '0 3 * * *'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js and PNPM
        uses: ./.github/actions/setup-node-pnpm

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-rust

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run npm audit
        run: pnpm audit --audit-level moderate

      - name: Run cargo audit
        run: cd src-tauri && cargo audit

      - name: Run cargo deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          manifest-path: src-tauri/Cargo.toml

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript', 'rust']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          config-file: ./.github/codeql/codeql-config.yml

      - name: Setup Node.js and PNPM
        if: matrix.language == 'javascript'
        uses: ./.github/actions/setup-node-pnpm

      - name: Setup Rust toolchain
        if: matrix.language == 'rust'
        uses: ./.github/actions/setup-rust

      - name: Install Linux dependencies
        if: matrix.language == 'rust'
        uses: ./.github/actions/install-linux-deps

      - name: Build frontend
        if: matrix.language == 'javascript'
        uses: ./.github/actions/build-frontend
        with:
          run-tests: 'false'
          run-type-check: 'false'
          run-lint: 'false'
          build-production: 'true'

      - name: Build backend
        if: matrix.language == 'rust'
        run: cd src-tauri && cargo build --release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate