name: Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run security scan daily at 3 AM UTC
    - cron: '0 3 * * *'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Install frontend dependencies
        run: pnpm install

      - name: Run npm audit
        run: pnpm audit --audit-level moderate

      - name: Run cargo audit
        run: cd src-tauri && cargo audit

      - name: Run cargo deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          manifest-path: src-tauri/Cargo.toml

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript', 'rust']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Install pnpm
        if: matrix.language == 'javascript'
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup Rust
        if: matrix.language == 'rust'
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.language == 'rust'
        run: |
          sudo apt-get update
          
          # Version-specific WebKit installation for Ubuntu 24.04 compatibility
          if [ "$(lsb_release -rs)" = "24.04" ]; then
            sudo apt-get install -y libwebkit2gtk-4.1-dev
          else
            sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev
          fi
          
          # Common dependencies (platform-agnostic)
          sudo apt-get install -y \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libssl-dev \
            pkg-config

      - name: Build frontend
        if: matrix.language == 'javascript'
        run: |
          pnpm install
          pnpm build

      - name: Build backend
        if: matrix.language == 'rust'
        run: cd src-tauri && cargo build --release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate